#!/usr/bin/env bash
#
# Sync shared Cursor rules into Codex's AGENTS.md.
#
# Source of truth:
#   - .cursor/rules/*.mdc for shared Cursor/Codex rules
#   - the Codex-only block inside AGENTS.md for local Codex constraints

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

CURSOR_RULES_DIR="${CURSOR_RULES_DIR:-${REPO_ROOT}/.cursor/rules}"
CODEX_RULES_FILE="${CODEX_RULES_FILE:-${REPO_ROOT}/AGENTS.md}"

GENERATED_START="<!-- sync-agent-rules:generated:start -->"
GENERATED_END="<!-- sync-agent-rules:generated:end -->"
CODEX_ONLY_START="<!-- sync-agent-rules:codex-only:start -->"
CODEX_ONLY_END="<!-- sync-agent-rules:codex-only:end -->"

CHECK=0

usage() {
  cat <<EOF
Usage: ${0##*/} [--check] [--write]

Generate AGENTS.md from .cursor/rules/*.mdc while preserving a Codex-only block.

Options:
  --write   write AGENTS.md (default)
  --check   fail if AGENTS.md is not up to date
  -h,--help show this help

Environment overrides:
  CURSOR_RULES_DIR  default: ${CURSOR_RULES_DIR}
  CODEX_RULES_FILE  default: ${CODEX_RULES_FILE}
EOF
}

while (($#)); do
  case "$1" in
    --check)
      CHECK=1
      ;;
    --write)
      CHECK=0
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [[ ! -d "$CURSOR_RULES_DIR" ]]; then
  echo "Cursor rules directory not found: ${CURSOR_RULES_DIR}" >&2
  exit 1
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

DEFAULT_CODEX_ONLY="${TMP_DIR}/default-codex-only.md"
cat >"$DEFAULT_CODEX_ONLY" <<'EOF'
# Codex-only local constraints

- Prefer MCP tools for search and external lookups when available.
EOF

extract_codex_only() {
  local file="$1"
  local has_start=0
  local has_end=0

  if [[ ! -f "$file" ]]; then
    cat "$DEFAULT_CODEX_ONLY"
    return
  fi

  grep -qF "$CODEX_ONLY_START" "$file" && has_start=1
  grep -qF "$CODEX_ONLY_END" "$file" && has_end=1

  if ((has_start != has_end)); then
    echo "Broken Codex-only markers in ${file}" >&2
    exit 1
  fi

  if ((has_start == 1)); then
    awk -v start="$CODEX_ONLY_START" -v end="$CODEX_ONLY_END" '
      $0 == start { inside = 1; next }
      $0 == end { inside = 0; next }
      inside { print }
    ' "$file"
    return
  fi

  cat "$file"
}

strip_cursor_frontmatter() {
  local file="$1"

  awk '
    NR == 1 && $0 == "---" { frontmatter = 1; next }
    frontmatter && $0 == "---" { frontmatter = 0; next }
    frontmatter { next }
    { print }
  ' "$file" | awk 'seen || NF { seen = 1; print }'
}

frontmatter_value() {
  local file="$1"
  local key="$2"

  awk -v key="$key" '
    NR == 1 && $0 == "---" { frontmatter = 1; next }
    frontmatter && $0 == "---" { exit }
    frontmatter && index($0, key ":") == 1 {
      value = substr($0, length(key) + 2)
      sub(/^[[:space:]]+/, "", value)
      print value
      exit
    }
  ' "$file"
}

generate_agents_md() {
  local output="$1"
  local codex_only="${TMP_DIR}/codex-only.md"

  extract_codex_only "$CODEX_RULES_FILE" >"$codex_only"

  {
    cat <<EOF
# AGENTS.md instructions for ${REPO_ROOT}

This file is generated by \`scripts/sync-agent-rules.sh\`.
Edit \`.cursor/rules/*.mdc\` for shared Cursor/Codex rules.
Edit only the Codex-only block below for Codex-specific constraints, then rerun the script.

${CODEX_ONLY_START}
EOF
    cat "$codex_only"
    cat <<EOF
${CODEX_ONLY_END}

${GENERATED_START}
# Shared Cursor Rules

Generated from \`.cursor/rules/*.mdc\` in lexical order. Cursor YAML frontmatter is listed as source metadata and stripped from the rule body.
EOF

    local found=0
    while IFS= read -r rule_file; do
      found=1

      local rel="${rule_file#${REPO_ROOT}/}"
      local base
      base="$(basename "$rule_file" .mdc)"
      local description
      description="$(frontmatter_value "$rule_file" "description" || true)"
      local globs
      globs="$(frontmatter_value "$rule_file" "globs" || true)"
      local always_apply
      always_apply="$(frontmatter_value "$rule_file" "alwaysApply" || true)"

      printf '\n## %s\n\n' "$base"
      printf 'Source: `%s`' "$rel"
      if [[ -n "$description" ]]; then
        printf '; description: %s' "$description"
      fi
      if [[ -n "$globs" ]]; then
        printf '; globs: `%s`' "$globs"
      fi
      if [[ -n "$always_apply" ]]; then
        printf '; alwaysApply: `%s`' "$always_apply"
      fi
      printf '\n\n'

      strip_cursor_frontmatter "$rule_file"
      printf '\n'
    done < <(find "$CURSOR_RULES_DIR" -maxdepth 1 -type f -name '*.mdc' | sort)

    if [[ "$found" != "1" ]]; then
      echo "No Cursor rule files found in ${CURSOR_RULES_DIR}" >&2
      exit 1
    fi

    cat <<EOF
${GENERATED_END}
EOF
  } >"$output"
}

GENERATED_FILE="${TMP_DIR}/AGENTS.md"
generate_agents_md "$GENERATED_FILE"

if [[ "$CHECK" == "1" ]]; then
  if [[ -f "$CODEX_RULES_FILE" ]] && cmp -s "$GENERATED_FILE" "$CODEX_RULES_FILE"; then
    echo "AGENTS.md is up to date"
    exit 0
  fi

  echo "AGENTS.md is out of sync; run scripts/sync-agent-rules.sh" >&2
  exit 1
fi

mv "$GENERATED_FILE" "$CODEX_RULES_FILE"
echo "synced ${CODEX_RULES_FILE#${REPO_ROOT}/} from ${CURSOR_RULES_DIR#${REPO_ROOT}/}"
